### ISSUE TITLE
ERROR: File "setup.py" not found

### ISSUE THREAD

**Issue by chagas98** [wikibib/wikibib#1]
When I was installing locally,  run `pip3 install -e .` gave me the error message :

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /path/to/wikibib
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.) 

Then I had to create a "setup.py" dummy file to run "pyproject.toml". 

setup.py file:
   ```
from setuptools import setup
 if __name__ == '__main__':
    setup()
```

It seems to be a limitation from `setuptools` (or did I do something wrong?) that I didn't understand very well, but I followed this workaround: https://stackoverflow.com/questions/70805902/pip-cannot-perform-editable-system-wide-install-of-pyproject-toml-project

**Comment by chagas98** [comment]
Before that, when running the `pip3 install -e .`, the error message was:
```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /path/to/wikibib
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.) 
```

**Comment by lubianat** [comment]
Thanks @chagas98!

It should not be needed in theory.

Can you tell me: 

* Your operational system
* Your version of pip (run `pip --version`)
* Your version of python3 (run `python3 --version`)


My guess is that it is a bug that has been corrected in more recent pip versions (https://stackoverflow.com/questions/69711606/how-to-install-a-package-using-pip-in-editable-mode-with-pyproject-toml). 

Anyways I'll create a dummy file, as more people might run into this issue.

**Comment by lubianat** [comment]
I'll close this for now, feel free to reopen it if that is still an issue.
