### ISSUE TITLE
Some issues I had with the documentation

### ISSUE THREAD

**Issue by jvfe** [wikibib/wikibib#3]
Great software and great work you did here!
However I had some issues parsing the documentation:

```
# Clone manubot/rootstock
git clone --single-branch https://github.com/wikibib/wikibib.git $REPO
cd $REPO
```
Nice to see the inspiration for your software doc, but I believe that meant to say "Clone wikibib/wikibib" hahah.

```
# Option A: Set origin URL using its web address via SSH
git remote set-url origin git@github.com:$OWNER/$REPO.git

Then create an empty repository on GitHub.
```

You say option A but then don't specify what Option B is. I was running the commands verbatim like you said - disclaimer I was listening to a podcast while doing it - but when I got to 'gh repo create' (Which I believe is what option B is) I got some errors setting the remote since it was already set before hand. I believe these two steps should be clearer.

Other than that, I think the documentation in SETUP.md and USAGE.md is very well written and easy to follow.

**Comment by lubianat** [comment]
Thanks @jvfe ! 

I've updated the docs, maybe it is clearer better now.

**Comment by jvfe** [comment]
Much clearer, yes. Thank you.
